In [2]:
import numpy as np
import torch
import matplotlib.pyplot as plt

def func(m,b = 0):
    x = np.linspace(0,10,100)
    y = m * x + b

    plt.plot(x, y)

    plt.show()
    return

# func(0.4)
# func(.2,1)

In [3]:
print("tensor x: ")

x= torch.tensor([[1, 3, 0],
                 [2 ,4 , 6]])

print(x)
# -1 means figure this dimension out automatically
print(x.view(-1)) # if you only pass 1 argument to view, it knows you only want a 1 dimensional matrix

print(x.view(3, -1)) # reshape it into three rows

print(x[:, 1:3]) # slicing, index the original array. look at column 1,2
#  : means all
# 1: 3, removes the 0 column

tensor x: 
tensor([[1, 3, 0],
        [2, 4, 6]])
tensor([1, 3, 0, 2, 4, 6])
tensor([[1, 3],
        [0, 2],
        [4, 6]])
tensor([[3, 0],
        [4, 6]])


In [4]:
print("tensor y: ")

y = torch.tensor([[[1,2,1],
                  [2,1,2]],
                  [[3,0,3],
                  [0,3,0]]])
print(y)
print(y[0:1,:,:])
print(y.transpose(0,1)) # swap dimension 0 and dimension 1 of tensor y
print(y.transpose(0,2)) # swap dimension 0 and dimension 2 of tensor y

tensor y: 
tensor([[[1, 2, 1],
         [2, 1, 2]],

        [[3, 0, 3],
         [0, 3, 0]]])
tensor([[[1, 2, 1],
         [2, 1, 2]]])
tensor([[[1, 2, 1],
         [3, 0, 3]],

        [[2, 1, 2],
         [0, 3, 0]]])
tensor([[[1, 3],
         [2, 0]],

        [[2, 0],
         [1, 3]],

        [[1, 3],
         [2, 0]]])


CIFAR10 dataset

In [7]:
import torch, torchvision

# run this later
# downloading CIFAR10 dataset 

cifar = torchvision.datasets.CIFAR10('./cifar10/', train = True, download=True)
x = torch.from_numpy(cifar.data).permute(0,3,1,2).float() / 255
print(x.dtype, x.size(), x.min().item(), x.max().item())

100%|██████████| 170M/170M [01:19<00:00, 2.14MB/s] 


Extracting ./cifar10/cifar-10-python.tar.gz to ./cifar10/
torch.float32 torch.Size([50000, 3, 32, 32]) 0.0 1.0


In [8]:
# narrows to the first images, converts to float
x = x[:48]

# saves these samples as a single image
torchvision.utils.save_image(x, 'cifar-4x12.png', nrow = 12, pad_value = 1.0)

In [9]:
print(x.size())

torch.Size([48, 3, 32, 32])


In [10]:
# Switches the row and column indexes
x.transpose_(2, 3)
torchvision.utils.save_image(x, 'cifar-4x12-rotated.png',
nrow = 12, pad_value = 1.0)

In [12]:
# Kills the green and blue channels
x[:, 1:3].fill_(0)
torchvision.utils.save_image(x, 'cifar-4x12-rotated-and-red.png',
nrow = 12, pad_value = 1.0)

In [17]:
# for efficiency reasons, different tensors can share the same data
# and modifying one will modify the other. By default do not make the 
# assumption that two tensors refer to different data in memory

a = torch.full((2, 3), 1)
print(a)

b = a.view(-1)
print(b)

a[1,1] = 2

print(a)
print(b)

b[0] = 9
print(a)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([1, 1, 1, 1, 1, 1])
tensor([[1, 1, 1],
        [1, 2, 1]])
tensor([1, 1, 1, 1, 2, 1])
tensor([[9, 1, 1],
        [1, 2, 1]])
tensor([9, 1, 1, 1, 2, 1])


when designing a model, only care about the big picture, not about how good it fits.

In [ ]:
import torch, numpy

data = torch.tensor(numpy.loadtxt('systolic-blood-pressure-vs-age.dat')) # we dont have the data
nb_samples = data.size(0)

x, y = torch. empty(nb_samples, 2), torch. empty(nb_samples, 1)

x[:, 0] = data[:, 0]
x[:, 1] = 1

y[:, 0] = data[:, 1]

alpha = torch.linalg.lstsq(x,y).solution

a,b = alpha[0,0].item(), alpha[1, 0].item()



FileNotFoundError: systolic-blood-pressure-vs-age.dat not found.